### ISSUE TITLE
What is the difference between tags and categories?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#66]

**Comment by wowthemesnet** [comment]
You want to keep your site organized with Categories. But at the same time, for SEO purposes you want to assign  the article as many keywords as possible. So consider tags as keywords.

_But_ I don't think it's that important on Github pages, which is why I never considered tags unless requested,  because as you know there are not actual permalinks for each categories & tags but `#`. 

Anyway, if not for SEO, the blogger might want to guide the user with related tags so...it doesn't hurt...

**Comment by GiacomoLaw** [comment]
Okay, thanks. I don’t think google takes keywords into account anymore, but I presume you can sort by tags?

Thanks!

**Comment by GiacomoLaw** [comment]
My idea for my site is having the anime category, and then tagging the article with the anime name. Is this possible?

Also, can tags have spaces?

Thanks!

**Comment by wowthemesnet** [comment]
Yes, I think that's great. This way if you write about more episodes, the user can get to the posts of the other episodes of the show easily.

Structure is same as category. We know we fixed the space for category so it should work in a similar way.

**Comment by GiacomoLaw** [comment]
Great, thanks for the great updates. Appreciate it!
